apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch-read-k8s-pod
spec:
  containers:
  - name: elasticsearch-read-k8s
    image: jm3015/elasticsearch-py
    env:
    - name: ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: elasticsearch-user-pass
          key: username
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-user-pass
          key: password
    command: ['python']
    args: [$SCRIPT, $(ELASTICSEARCH_USERNAME), $(ELASTICSEARCH_PASSWORD)]
  restartPolicy: Never