apiVersion: v1
kind: Pod
metadata:
  name: mongodb-write-k8s-pod
spec:
  containers:
  - name: mongodb-write-k8s
    image: jm3015/mongodb-py
    # resources:
    #   requests:
    #     memory: "1Gi"
    #     cpu: 1
    #   limits:
    #     memory: "2Gi"
    #     cpu: 1
    env:
    - name: MINIO_ACCESSKEY
      valueFrom:
        secretKeyRef:
          name: minio-access-secret
          key: accesskey
    - name: MINIO_SECRETKEY
      valueFrom:
        secretKeyRef:
          name: minio-access-secret
          key: secretkey
    - name: MONGODB_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongodb-user-pass
          key: username
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongodb-user-pass
          key: password
    command: ['python']
    args: [$SCRIPT, $(MINIO_ACCESSKEY), $(MINIO_SECRETKEY), $(MONGODB_USERNAME), $(MONGODB_PASSWORD)]
  restartPolicy: Never