FROM apache/spark-py:v3.2.1

USER root

ARG POMFILE=delta-pom.xml

RUN apt-get update && apt-get install -y maven

COPY ${POMFILE} /opt

RUN mvn -f /opt/${POMFILE} dependency:copy-dependencies -DoutputDirectory=/opt/packages
RUN cp /opt/packages/* /opt/spark/jars

RUN pip3 install delta-spark==1.2.0 delta-sharing
RUN pip3 install pytz

COPY scripts /opt/spark/work-dir

ENV SPARK_HOME /opt/spark